### ISSUE TITLE
Undefined rule function-calc-no-invalid

### ISSUE THREAD

**Issue by darrenyung** [DeloitteDigitalAPAC/stylelint-config-deloitte#6]
I get this error when I run linters with the package version post v1.1.0

`stylelint --config .stylelintrc  -i .stylelintignore "source/assets/scss/**/*.scss"

Error: Undefined rule function-calc-no-invalid
    at Object.keys.forEach.ruleName (C:\Projects\xx\node_modules\stylelint\lib\augmentConfig.js:279:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (C:\Projects\xx\node_modules\stylelint\lib\augmentConfig.js:275:29)
    at augmentConfigBasic.then.then.then.then.augmentedConfig (C:\Projects\xx\node_modules\stylelint\lib\augmentConfig.js:84:12)`

**Comment by noahbald** [comment]
This is also causing issues with me; function-calc-no-invalid is deprecated and should be removed
https://github.com/stylelint/stylelint/issues/5713#issuecomment-968114664
